---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[tw-audit-cis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
