---
driver:
  name: ec2
  aws_ssh_key_id: aws-vasi
  region: eu-central-1
  instance_type: t2.micro
  security_group_ids: ["sg-50ff3f3b"]
  associate_public_ip: true
  interface: dns

transport:
  ssh_key: ~/.ssh/aws-vasi.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:
