---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  # nodes_path: test/fixtures/nodes
  # clients_path: test/fixtures/clients
  # environments_path: test/fixtures/environments

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - role[base]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      authorization:
        sudo:
          users: ['kitchen', 'vagrant']
          passwordless: true
          include_sudoers_d: true
